version: '3.1'

services:

  wordpress:
    image: wordpress:6-php7.4-fpm
    restart: always

    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./requirements/data/html:/var/www/wordpress

    networks:
      - net

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - ./requirements/data/mysql:/var/lib/mysql
    networks:
      - net

  nginx:
    build: requirements/nginx
    volumes:
      - ./requirements/nginx:/etc/nginx/conf.d
      - ./requirements/data/html:/var/www/wordpress
    ports:
      # - 8081:80
      - 443:443
    links:
      - wordpress

    networks:
      - net

networks:
  net:
    driver: bridge


# volumes:
  # wordpress1:
  # db:
