version: '3.8'

services:

  # nginx:
  #   build: requirements/nginx
  #   volumes:
  #     - ./requirements/nginx/tools/:/etc/nginx/sites-enabled/
  #     - /home/${USER}/data/wp:/var/www/wordpress

  #   stdin_open : true
  #   tty: true
  #   ports:
  #     - 443:443

  #   depends_on:
  #     - wp

  #   networks:
  #     - net


  wp:
    build: requirements/wordpress
  
    restart: always

    stdin_open : true
    tty: true
    env_file: .env
    volumes:
      - wp_v:/var/www/html/wordpress/

    ports:
      - 80:9000

    depends_on:
      - db

    networks:
      - net

  db:
    build: requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db_v:/var/lib/mysql
    networks:
      - net

  

networks:
  net:
    driver: bridge


volumes:
  wp_v:
      driver: local
      driver_opts:
        device: ${HOME}/data/wp
        o: bind
        type: none

  db_v:
      driver: local
      driver_opts:
        device: ${HOME}/data/db
        o: bind
        type: none