version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./requirements/data/html:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./requirements/data/mysql:/var/lib/mysql
  nginx:
    image: nginx:latest
    volumes:
      - ./requirements/nginx:/etc/nginx/conf.d
      - ./requirements/data/html:/var/www/html
    ports:
      - 8081:80
    links:
      - wordpress
# volumes:
  # wordpress1:
  # db:
