version: '3.9'

networks:
  project:
    driver: bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp

services:
  mariadb:

    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - project
    restart: always

  wordpress:

    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - project
    depends_on:
      - mariadb
    restart: always

  nginx:
  
    build: ./requirements/nginx
    hostname: localhost
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - project
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: always
